require_relative '../models/choice'

choices = [
 {beginning_decision_point_id: 1, ending_decision_point_id: 2, name: 'Sugar puffs'},
 {beginning_decision_point_id: 1, ending_decision_point_id: 2, name: 'Frosties'},
 {beginning_decision_point_id: 2, ending_decision_point_id: 3, name: 'Thompson Twins'},
 {beginning_decision_point_id: 2, ending_decision_point_id: 3, name: 'Now 2'},
 {beginning_decision_point_id: 3, ending_decision_point_id: 3, name: 'Accept'},
 {beginning_decision_point_id: 3, ending_decision_point_id: 4, name: 'Refuse'},
 {beginning_decision_point_id: 4, ending_decision_point_id: 5, name: 'No'},
 {beginning_decision_point_id: 5, ending_decision_point_id: 6, name: 'No'},
 {beginning_decision_point_id: 6, ending_decision_point_id: 7, name: 'Phaedra'},
 {beginning_decision_point_id: 7, ending_decision_point_id: 8, name: 'Throw tea over computer'},
 {beginning_decision_point_id: 8, ending_decision_point_id: 7, name: 'Go back'},
 {beginning_decision_point_id: 7, ending_decision_point_id: 9, name: 'Shout at dad'},
 {beginning_decision_point_id: 9, ending_decision_point_id: 10, name: 'Follow Colin'},
 {beginning_decision_point_id: 10, ending_decision_point_id: 11, name: 'No - do not take acid'},
 {beginning_decision_point_id: 11, ending_decision_point_id: 12, name: 'Stefan jumps'},
 {beginning_decision_point_id: 12, ending_decision_point_id: 11, name: 'Go back'},
 {beginning_decision_point_id: 11, ending_decision_point_id: 13, name: 'Colin'},
 {beginning_decision_point_id: 13, ending_decision_point_id: 14, name: 'Bite nails'},
 {beginning_decision_point_id: 14, ending_decision_point_id: 15, name: 'Throw them away'},
 {beginning_decision_point_id: 15, ending_decision_point_id: 16, name: 'Destroy computer'},
 {beginning_decision_point_id: 16, ending_decision_point_id: 15, name: 'Go back'},
 {beginning_decision_point_id: 15, ending_decision_point_id: 17, name: 'Hit desk'},
 {beginning_decision_point_id: 17, ending_decision_point_id: 18, name: 'Pick up family photo'},
 {beginning_decision_point_id: 18, ending_decision_point_id: 19, name: 'Throw tea over computer'},
 {beginning_decision_point_id: 19, ending_decision_point_id: 20, name: 'Netflix'},
 {beginning_decision_point_id: 20, ending_decision_point_id: 21, name: 'Try to explain'},
 {beginning_decision_point_id: 21, ending_decision_point_id: 22, name: 'Tell him more'},
 {beginning_decision_point_id: 22, ending_decision_point_id: 23, name: 'Fuck yeah'},
 {beginning_decision_point_id: 23, ending_decision_point_id: 24, name: 'Fight her'},
 {beginning_decision_point_id: 24, ending_decision_point_id: 25, name: 'Balls'},
 {beginning_decision_point_id: 25, ending_decision_point_id: 26, name: 'Talk about mom (no choice)'},
 {beginning_decision_point_id: 26, ending_decision_point_id: 17, name: 'No do not go with mom (no choice)'},
 {beginning_decision_point_id: 17, ending_decision_point_id: 28, name: 'Pick up book'},
 {beginning_decision_point_id: 28, ending_decision_point_id: 19, name: 'PAX'},
 {beginning_decision_point_id: 19, ending_decision_point_id: 20, name: 'Netflix'},
 {beginning_decision_point_id: 20, ending_decision_point_id: 21, name: 'Try to explain'},
 {beginning_decision_point_id: 21, ending_decision_point_id: 22, name: 'Stop the conversation'},
 {beginning_decision_point_id: 22, ending_decision_point_id: 23, name: 'Yes'},
 {beginning_decision_point_id: 23, ending_decision_point_id: 29, name: 'Leap through window'},
 {beginning_decision_point_id: 29, ending_decision_point_id: 19, name: 'Who is there (no choice)'},
 {beginning_decision_point_id: 19, ending_decision_point_id: 30, name: 'BS symbol'},
 {beginning_decision_point_id: 30, ending_decision_point_id: 31, name: 'Back off'},
 {beginning_decision_point_id: 31, ending_decision_point_id: 19, name: 'Pick up photo'},
 {beginning_decision_point_id: 19, ending_decision_point_id: 30, name: 'BS symbol'},
 {beginning_decision_point_id: 30, ending_decision_point_id: 32, name: 'Kill dad'},
 {beginning_decision_point_id: 32, ending_decision_point_id: 33, name: 'Chop up body'},
 {beginning_decision_point_id: 33, ending_decision_point_id: 34, name: 'Throw tea over computer (Pearl version)'},
 {beginning_decision_point_id: 34, ending_decision_point_id: 32, name: 'Chop or bury body (no choice)'},
 {beginning_decision_point_id: 32, ending_decision_point_id: 35, name: 'Bury body'},
 {beginning_decision_point_id: 35, ending_decision_point_id: 36, name: 'No will not have it done'},
 {beginning_decision_point_id: 36, ending_decision_point_id: 37, name: 'Get rabbit from dad (no choice)'},
 {beginning_decision_point_id: 37, ending_decision_point_id: 38, name: 'PAC'},
 {beginning_decision_point_id: 38, ending_decision_point_id: 39, name: 'PACS'},
 {beginning_decision_point_id: 39, ending_decision_point_id: 36, name: 'Enter wrong number'},
 {beginning_decision_point_id: 36, ending_decision_point_id: 37, name: 'Get rabbit from dad (no choice)'},
 {beginning_decision_point_id: 37, ending_decision_point_id: 40, name: 'TOY'},
 {beginning_decision_point_id: 40, ending_decision_point_id: 41, name: 'No do not go on train'},
 {beginning_decision_point_id: 41, ending_decision_point_id: 42, name: 'BS symbol'},
 {beginning_decision_point_id: 42, ending_decision_point_id: 43, name: 'Let Colin go'},
]

Choice.initialize_data = choices
